# Generated by Django 5.2.7 on 2026-06-06 07:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('category', models.CharField(default='Leadership', max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MYP Constitution', max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='constitution/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Constitution',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Specialized programmes, mentorship and projects led by member experts.')),
                ('icon', models.CharField(help_text='FontAwesome icon (e.g., fa-crown, fa-chart-line)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.CharField(help_text='e.g., 12 Jul • Meru', max_length=50)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fa-calendar-alt', max_length=50)),
                ('registration_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('council', 'Executive Council'), ('department', 'Department Leadership')], default='council', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Ongoing', max_length=50)),
                ('location', models.CharField(default='Multiple counties', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Main logo (recommended: 200x60px)', null=True, upload_to='logo/')),
                ('logo_footer', models.ImageField(blank=True, help_text='Footer logo (recommended: 150x50px)', null=True, upload_to='logo/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser tab icon', null=True, upload_to='logo/')),
                ('hero_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('hero_background', models.ImageField(blank=True, help_text='Hero background image (1920x1080px)', null=True, upload_to='hero/')),
                ('hero_video', models.FileField(blank=True, help_text='Hero background video (MP4 format)', null=True, upload_to='hero/')),
                ('hero_tagline', models.CharField(default='MT. KENYA · NON-PROFIT · YOUTH-LED', max_length=100)),
                ('hero_title_line1', models.CharField(default='Empowering', max_length=100)),
                ('hero_title_line2', models.CharField(default='Professionals', max_length=100)),
                ('hero_title_line3', models.CharField(default='Transforming Communities', max_length=100)),
                ('hero_subtitle', models.TextField(default='Meru Young Professionals unites a generation of leaders, innovators and changemakers from the Mt. Kenya region and beyond.')),
                ('become_member_text', models.CharField(default='Become a Member', max_length=50)),
                ('become_member_url', models.CharField(default='/members/register/', max_length=200)),
                ('join_us_text', models.CharField(default='Join Us', max_length=50)),
                ('join_us_url', models.CharField(default='/members/register/', max_length=200)),
                ('welcome_title', models.CharField(default='A network rooted in Mt. Kenya, reaching nation-wide.', max_length=200)),
                ('welcome_content', ckeditor_uploader.fields.RichTextUploadingField(default='We bring together young professionals committed to leadership, innovation, entrepreneurship, mentorship, environmental conservation and economic empowerment — anchored in service and excellence.')),
                ('learn_more_url', models.CharField(default='/about/', max_length=200)),
                ('mission_text', models.TextField(default='Empower young professionals through leadership, innovation and service.')),
                ('vision_text', models.TextField(default='The leading network of transformative professionals across Kenya.')),
                ('community_text', models.CharField(default='1,200+ professionals collaborating to drive measurable impact.', max_length=200)),
                ('innovation_text', models.CharField(default='Bold ideas, applied locally for lasting transformation.', max_length=200)),
                ('core_values_title', models.CharField(default='CORE VALUES', max_length=100)),
                ('core_values_subtitle', models.CharField(default='The principles that guide every member', max_length=200)),
                ('departments_title', models.CharField(default='DEPARTMENTS', max_length=100)),
                ('departments_subtitle', models.CharField(default='Where impact takes shape', max_length=200)),
                ('projects_title', models.CharField(default='FEATURED PROJECTS', max_length=100)),
                ('projects_subtitle', models.CharField(default='Building tomorrow, today.', max_length=200)),
                ('events_title', models.CharField(default='UPCOMING EVENTS', max_length=100)),
                ('events_subtitle', models.CharField(default="Don't miss out.", max_length=200)),
                ('blog_title', models.CharField(default='LATEST NEWS & BLOGS', max_length=100)),
                ('blog_subtitle', models.CharField(default='Voices of MYP', max_length=200)),
                ('partners_title', models.CharField(default='PARTNERS & SPONSORS', max_length=100)),
                ('view_all_departments_text', models.CharField(default='View all →', max_length=50)),
                ('explore_projects_text', models.CharField(default='Explore projects', max_length=50)),
                ('view_calendar_text', models.CharField(default='View calendar', max_length=50)),
                ('all_articles_text', models.CharField(default='All articles →', max_length=50)),
                ('testimonial_text', models.TextField(default='MYP gave me a community of mentors and a platform to launch my agribusiness. Today we employ 14 young people in Meru.')),
                ('testimonial_author', models.CharField(default='Wanjiru K.', max_length=100)),
                ('testimonial_role', models.CharField(default='MYP Member since 2022', max_length=100)),
                ('cta_title', models.CharField(default='Ready to make an impact?', max_length=200)),
                ('cta_subtitle', models.CharField(default='Join 1,200+ young professionals transforming Kenya — one project, one community at a time.', max_length=300)),
                ('cta_button_text', models.CharField(default='Become a Member', max_length=50)),
                ('cta_button_url', models.CharField(default='/members/register/', max_length=200)),
                ('contact_button_text', models.CharField(default='Contact Us', max_length=50)),
                ('contact_button_url', models.CharField(default='/contact/', max_length=200)),
                ('footer_about', models.TextField(default='Empowering Professionals, Transforming Communities across the Mt. Kenya region and beyond.')),
                ('footer_explore_title', models.CharField(default='EXPLORE', max_length=50)),
                ('footer_engage_title', models.CharField(default='ENGAGE', max_length=50)),
                ('footer_contact_title', models.CharField(default='CONTACT', max_length=50)),
                ('footer_address', models.CharField(default='Meru Town, Kenya', max_length=200)),
                ('footer_email', models.EmailField(default='info@myp.or.ke', max_length=254)),
                ('footer_phone', models.CharField(default='+254 700 000 000', max_length=50)),
                ('footer_copyright', models.CharField(default='2026 Meru Young Professionals. All rights reserved.', max_length=200)),
                ('footer_tagline', models.CharField(default='Non-political · Non-profit · Youth-Led', max_length=200)),
                ('primary_color', models.CharField(default='#0A7D3B', help_text='Primary brand color', max_length=20)),
                ('secondary_color', models.CharField(default='#D32F2F', help_text='Secondary brand color', max_length=20)),
                ('dark_color', models.CharField(default='#1A1A1A', help_text='Dark color for backgrounds', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., MEMBERS, DEPARTMENTS', max_length=50)),
                ('value', models.CharField(help_text='e.g., 1,200+, 8+', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
