# Generated by Django 5.2.7 on 2026-06-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('highest_qualification', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('membership_type', models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('corporate', 'Corporate')], default='professional', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Preferred department', max_length=100)),
                ('reason_for_joining', models.TextField()),
                ('expectations', models.TextField(blank=True)),
                ('referral_source', models.CharField(blank=True, max_length=200)),
                ('referred_by', models.CharField(blank=True, max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='membership/cvs/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='membership/profiles/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='membership/ids/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('membership_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
