# Generated by Django 5.2.3 on 2025-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electrical', 'Electrical & Electronics'), ('plumbing', 'Plumbing'), ('civil', 'Civil Engineering'), ('ict', 'ICT Services'), ('mechanical', 'Mechanical'), ('automotive', 'Automotive Repair')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(choices=[('electrical', 'Electrical & Electronics'), ('plumbing', 'Plumbing'), ('civil', 'Civil Engineering'), ('ict', 'ICT Services'), ('mechanical', 'Mechanical'), ('automotive', 'Automotive Repair')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
