# Generated by Django 5.2.3 on 2025-06-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
