# Generated by Django 5.2.4 on 2025-07-05 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='PAYMENT_PENDING', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('permit_pdf', models.FileField(blank=True, null=True, upload_to='permits/')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
