# Generated by Django 5.2.1 on 2025-06-30 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('PP1', 'Pre-Primary 1'), ('PP2', 'Pre-Primary 2')], max_length=10)),
                ('stream', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pre-Primary', 'Pre-Primary (PP1-PP2)'), ('Lower Primary', 'Lower Primary (Grade 1-3)'), ('Upper Primary', 'Upper Primary (Grade 4-6)'), ('Junior Secondary', 'Junior Secondary (Grade 7-9)'), ('Senior Secondary', 'Senior Secondary (Grade 10-12)')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='section',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='r_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='seating_capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='room',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Room A', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('7:30 - 8:00', 'Morning Assembly'), ('8:00 - 8:40', '8:00 - 8:40'), ('8:40 - 9:20', '8:40 - 9:20'), ('9:20 - 10:00', '9:20 - 10:00'), ('10:00 - 10:20', 'Tea Break'), ('10:20 - 11:00', '10:20 - 11:00'), ('11:00 - 11:40', '11:00 - 11:40'), ('11:40 - 12:20', '11:40 - 12:20'), ('12:20 - 1:00', '12:20 - 1:00'), ('1:00 - 2:00', 'Lunch Break'), ('2:00 - 2:40', '2:00 - 2:40'), ('2:40 - 3:20', '2:40 - 3:20'), ('3:20 - 4:00', 'Games/Remedial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.classlevel')),
            ],
            options={
                'unique_together': {('class_level', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttgen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.schoollevel'),
        ),
        migrations.CreateModel(
            name='CBCSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Literacy', 'Literacy'), ('Kiswahili', 'Kiswahili'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Environmental', 'Environmental Activities'), ('Hygiene', 'Hygiene and Nutrition'), ('Religious', 'Religious Education'), ('Movement', 'Movement and Creative'), ('Art', 'Art and Craft'), ('Music', 'Music'), ('Science', 'Science and Technology'), ('Social', 'Social Studies'), ('Agriculture', 'Agriculture'), ('Home Science', 'Home Science'), ('Business', 'Business Studies'), ('Sports', 'Sports and Physical Education'), ('Life Skills', 'Life Skills Education')], max_length=50)),
                ('is_core', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.schoollevel')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsc_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subjects', models.ManyToManyField(to='ttgen.cbcsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.meetingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.cbcsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.classtimetable')),
            ],
            options={
                'unique_together': {('room', 'meeting_time'), ('teacher', 'meeting_time'), ('timetable', 'meeting_time')},
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
