# Generated by Django 5.2.4 on 2025-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, help_text='e.g., +2547XXXXXXX', max_length=20, null=True),
        ),
    ]
