# Generated by Django 5.2.4 on 2025-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='applicable_systems',
            field=models.ManyToManyField(blank=True, to='timetable.system'),
        ),
    ]
