# Generated by Django 5.2.7 on 2026-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MYP Constitution', max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='constitution/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Constitution',
            },
        ),
    ]
