# Generated by Django 5.2.7 on 2026-06-08 10:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constitution',
            options={'ordering': ['-version'], 'verbose_name_plural': 'Constitution'},
        ),
        migrations.AddField(
            model_name='constitution',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constitution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='constitution',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Constitution content for online reading - supports HTML formatting'),
        ),
        migrations.AlterField(
            model_name='constitution',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF version for download', null=True, upload_to='constitution/'),
        ),
    ]
