# Generated by Django 5.2.7 on 2026-06-08 10:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constitution', '0002_alter_constitution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constitution',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Constitution content for online reading', null=True),
        ),
        migrations.AlterField(
            model_name='constitution',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='constitution/'),
        ),
    ]
