# Generated by Django 5.2.7 on 2026-06-08 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/'),
        ),
        migrations.AddField(
            model_name='department',
            name='leader_image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/leaders/'),
        ),
        migrations.AddField(
            model_name='department',
            name='leader_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='leader_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='project_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default='Specialized programmes, mentorship and projects led by member experts.'),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.CharField(help_text='FontAwesome icon class (e.g., fa-crown, fa-chart-line)', max_length=50),
        ),
    ]
